//the data as string .. was generated by the code below:

export const tasks = [
  {
    payoff: {
      A: { 101: 53, 102: 77, 103: 75, 104: 36, 105: 24, 106: 41 },
      B: { 101: 44, 102: 39, 103: 66, 104: 44, 105: 39, 106: 27 },
      C: { 101: 31, 102: 35, 103: 65, 104: 21, 105: 76, 106: 58 },
      D: { 101: 48, 102: 66, 103: 30, 104: 37, 105: 80, 106: 59 },
      E: { 101: 66, 102: 78, 103: 27, 104: 74, 105: 48, 106: 57 },
      F: { 101: 82, 102: 31, 103: 67, 104: 76, 105: 37, 106: 53 },
      G: { 101: 56, 102: 25, 103: 37, 104: 47, 105: 24, 106: 45 },
      H: { 101: 73, 102: 55, 103: 42, 104: 69, 105: 34, 106: 35 }
    },
    _id: "0",
    difficulty: "Training - Medium",
    students: ["A", "B", "C", "D", "E", "F", "G", "H"],
    rooms: [101, 102, 103, 104, 105, 106],
    constraints: [
      {
        _id: 0,
        type: 1,
        pair: ["C", "D"],
        text: "can't live in the same room"
      },
      { _id: 1, type: 2, pair: ["D", "E"], text: "must be neighbors" },
      {
        _id: 2,
        type: 3,
        pair: ["E", "H"],
        text: "can't live in the same room or be neighbors"
      },
      {
        _id: 3,
        type: 1,
        pair: ["F", "H"],
        text: "can't live in the same room"
      },
      { _id: 1, type: 2, pair: ["A", "F"], text: "must be neighbours" }
    ],
    optimal: 567,
    computeTime: 2.99,
    usedIn: "step1",
    study: "chainExperiment"
  },
  {
    "payoff": {
      "A": {
        "101": 18,
        "102": 41,
        "103": 36,
        "104": 56,
        "105": 51,
        "106": 76
      },
      "B": {
        "101": 16,
        "102": 58,
        "103": 60,
        "104": 29,
        "105": 13,
        "106": 20
      },
      "C": {
        "101": 58,
        "102": 57,
        "103": 25,
        "104": 84,
        "105": 64,
        "106": 18
      },
      "D": {
        "101": 24,
        "102": 30,
        "103": 24,
        "104": 36,
        "105": 56,
        "106": 86
      },
      "E": {
        "101": 4,
        "102": 31,
        "103": 3,
        "104": 73,
        "105": 93,
        "106": 9
      },
      "F": {
        "101": 17,
        "102": 6,
        "103": 45,
        "104": 5,
        "105": 5,
        "106": 8
      },
      "G": {
        "101": 54,
        "102": 34,
        "103": 66,
        "104": 52,
        "105": 98,
        "106": 99
      },
      "H": {
        "101": 17,
        "102": 86,
        "103": 1,
        "104": 35,
        "105": 84,
        "106": 6
      }
    },
    "_id": "11707",
    "difficulty": "Hard",
    "students": [
      "A",
      "B",
      "C",
      "D",
      "E",
      "F",
      "G",
      "H"
    ],
    "rooms": [
      101,
      102,
      103,
      104,
      105,
      106
    ],
    "constraints": [
      {
        "_id": 0,
        "type": 3,
        "pair": [
          "D",
          "G"
        ],
        "text": "can't live in the same room or be neighbors"
      },
      {
        "_id": 1,
        "type": 0,
        "pair": [
          "G",
          "H"
        ],
        "text": "must live in the same room"
      },
      {
        "_id": 2,
        "type": 2,
        "pair": [
          "A",
          "D"
        ],
        "text": "must be neighbors"
      },
      {
        "_id": 3,
        "type": 0,
        "pair": [
          "D",
          "F"
        ],
        "text": "must live in the same room"
      },
      {
        "_id": 4,
        "type": 0,
        "pair": [
          "C",
          "G"
        ],
        "text": "must live in the same room"
      },
      {
        "_id": 5,
        "type": 1,
        "pair": [
          "A",
          "F"
        ],
        "text": "can't live in the same room"
      },
      {
        "_id": 6,
        "type": 1,
        "pair": [
          "A",
          "G"
        ],
        "text": "can't live in the same room"
      },
      {
        "_id": 7,
        "type": 3,
        "pair": [
          "A",
          "E"
        ],
        "text": "can't live in the same room or be neighbors"
      }
    ],
    "optimal": 509,
    "prop_sat": 0.0003643689986282579,
    "sat_std_norm": 0.12111697445221246,
    "sat_std": 61.64853999617615,
    "min_sat_score": 193,
    "med_sat_score": 320.3333333333333,
    "med_sat_score_norm": 0.6293385723641126,
    "hc_gap_norm": 0.3889980353634578
  },
  {
    "payoff": {
      "A": {
        "101": 10,
        "102": 23,
        "103": 57,
        "104": 23,
        "105": 24,
        "106": 77
      },
      "B": {
        "101": 73,
        "102": 10,
        "103": 62,
        "104": 68,
        "105": 44,
        "106": 18
      },
      "C": {
        "101": 98,
        "102": 54,
        "103": 94,
        "104": 24,
        "105": 63,
        "106": 80
      },
      "D": {
        "101": 12,
        "102": 9,
        "103": 75,
        "104": 20,
        "105": 14,
        "106": 2
      },
      "E": {
        "101": 52,
        "102": 45,
        "103": 75,
        "104": 72,
        "105": 51,
        "106": 13
      },
      "F": {
        "101": 78,
        "102": 13,
        "103": 34,
        "104": 13,
        "105": 10,
        "106": 70
      },
      "G": {
        "101": 16,
        "102": 4,
        "103": 49,
        "104": 59,
        "105": 80,
        "106": 91
      },
      "H": {
        "101": 25,
        "102": 34,
        "103": 74,
        "104": 17,
        "105": 35,
        "106": 26
      }
    },
    "_id": "12824",
    "difficulty": "Hard",
    "students": [
      "A",
      "B",
      "C",
      "D",
      "E",
      "F",
      "G",
      "H"
    ],
    "rooms": [
      101,
      102,
      103,
      104,
      105,
      106
    ],
    "constraints": [
      {
        "_id": 0,
        "type": 0,
        "pair": [
          "G",
          "H"
        ],
        "text": "must live in the same room"
      },
      {
        "_id": 1,
        "type": 3,
        "pair": [
          "D",
          "H"
        ],
        "text": "can't live in the same room or be neighbors"
      },
      {
        "_id": 2,
        "type": 2,
        "pair": [
          "D",
          "F"
        ],
        "text": "must be neighbors"
      },
      {
        "_id": 3,
        "type": 0,
        "pair": [
          "A",
          "B"
        ],
        "text": "must live in the same room"
      },
      {
        "_id": 4,
        "type": 2,
        "pair": [
          "F",
          "H"
        ],
        "text": "must be neighbors"
      },
      {
        "_id": 5,
        "type": 0,
        "pair": [
          "A",
          "E"
        ],
        "text": "must live in the same room"
      },
      {
        "_id": 6,
        "type": 0,
        "pair": [
          "E",
          "F"
        ],
        "text": "must live in the same room"
      },
      {
        "_id": 7,
        "type": 1,
        "pair": [
          "B",
          "C"
        ],
        "text": "can't live in the same room"
      }
    ],
    "optimal": 464,
    "prop_sat": 2.381496723060509e-05,
    "sat_std_norm": 0.12976710815743028,
    "sat_std": 60.21193818504766,
    "min_sat_score": 231,
    "med_sat_score": 343.85,
    "med_sat_score_norm": 0.7410560344827587,
    "hc_gap_norm": 0.46336206896551724
  },
  {
    "payoff": {
      "A": {
        "101": 57,
        "102": 37,
        "103": 1,
        "104": 15,
        "105": 24,
        "106": 16
      },
      "B": {
        "101": 14,
        "102": 67,
        "103": 58,
        "104": 58,
        "105": 96,
        "106": 75
      },
      "C": {
        "101": 37,
        "102": 81,
        "103": 15,
        "104": 67,
        "105": 87,
        "106": 21
      },
      "D": {
        "101": 22,
        "102": 57,
        "103": 47,
        "104": 52,
        "105": 8,
        "106": 35
      },
      "E": {
        "101": 80,
        "102": 87,
        "103": 87,
        "104": 13,
        "105": 66,
        "106": 99
      },
      "F": {
        "101": 47,
        "102": 61,
        "103": 62,
        "104": 42,
        "105": 9,
        "106": 26
      },
      "G": {
        "101": 7,
        "102": 51,
        "103": 75,
        "104": 9,
        "105": 56,
        "106": 31
      },
      "H": {
        "101": 90,
        "102": 93,
        "103": 47,
        "104": 69,
        "105": 14,
        "106": 77
      }
    },
    "_id": "14375",
    "difficulty": "Hard",
    "students": [
      "A",
      "B",
      "C",
      "D",
      "E",
      "F",
      "G",
      "H"
    ],
    "rooms": [
      101,
      102,
      103,
      104,
      105,
      106
    ],
    "constraints": [
      {
        "_id": 0,
        "type": 0,
        "pair": [
          "A",
          "C"
        ],
        "text": "must live in the same room"
      },
      {
        "_id": 1,
        "type": 3,
        "pair": [
          "B",
          "G"
        ],
        "text": "can't live in the same room or be neighbors"
      },
      {
        "_id": 2,
        "type": 2,
        "pair": [
          "C",
          "E"
        ],
        "text": "must be neighbors"
      },
      {
        "_id": 3,
        "type": 2,
        "pair": [
          "A",
          "D"
        ],
        "text": "must be neighbors"
      },
      {
        "_id": 4,
        "type": 3,
        "pair": [
          "D",
          "F"
        ],
        "text": "can't live in the same room or be neighbors"
      },
      {
        "_id": 5,
        "type": 1,
        "pair": [
          "A",
          "D"
        ],
        "text": "can't live in the same room"
      },
      {
        "_id": 6,
        "type": 2,
        "pair": [
          "A",
          "F"
        ],
        "text": "must be neighbors"
      },
      {
        "_id": 7,
        "type": 2,
        "pair": [
          "F",
          "H"
        ],
        "text": "must be neighbors"
      }
    ],
    "optimal": 563,
    "prop_sat": 0.0003334095412284713,
    "sat_std_norm": 0.13116635070154584,
    "sat_std": 73.84665544497031,
    "min_sat_score": 165,
    "med_sat_score": 382.29285714285714,
    "med_sat_score_norm": 0.6790281654402436,
    "hc_gap_norm": 0.42095914742451157
  },
  {
    "payoff": {
      "A": {
        "101": 72,
        "102": 42,
        "103": 83,
        "104": 10,
        "105": 47,
        "106": 38
      },
      "B": {
        "101": 99,
        "102": 20,
        "103": 97,
        "104": 30,
        "105": 61,
        "106": 68
      },
      "C": {
        "101": 41,
        "102": 18,
        "103": 43,
        "104": 14,
        "105": 89,
        "106": 81
      },
      "D": {
        "101": 72,
        "102": 11,
        "103": 4,
        "104": 84,
        "105": 91,
        "106": 92
      },
      "E": {
        "101": 20,
        "102": 64,
        "103": 65,
        "104": 87,
        "105": 11,
        "106": 86
      },
      "F": {
        "101": 29,
        "102": 77,
        "103": 49,
        "104": 98,
        "105": 45,
        "106": 89
      },
      "G": {
        "101": 36,
        "102": 50,
        "103": 38,
        "104": 22,
        "105": 24,
        "106": 2
      },
      "H": {
        "101": 88,
        "102": 50,
        "103": 78,
        "104": 37,
        "105": 82,
        "106": 35
      }
    },
    "_id": "14407",
    "difficulty": "Hard",
    "students": [
      "A",
      "B",
      "C",
      "D",
      "E",
      "F",
      "G",
      "H"
    ],
    "rooms": [
      101,
      102,
      103,
      104,
      105,
      106
    ],
    "constraints": [
      {
        "_id": 0,
        "type": 0,
        "pair": [
          "A",
          "E"
        ],
        "text": "must live in the same room"
      },
      {
        "_id": 1,
        "type": 0,
        "pair": [
          "B",
          "G"
        ],
        "text": "must live in the same room"
      },
      {
        "_id": 2,
        "type": 0,
        "pair": [
          "B",
          "C"
        ],
        "text": "must live in the same room"
      },
      {
        "_id": 3,
        "type": 2,
        "pair": [
          "A",
          "D"
        ],
        "text": "must be neighbors"
      },
      {
        "_id": 4,
        "type": 0,
        "pair": [
          "A",
          "C"
        ],
        "text": "must live in the same room"
      },
      {
        "_id": 5,
        "type": 0,
        "pair": [
          "A",
          "G"
        ],
        "text": "must live in the same room"
      },
      {
        "_id": 6,
        "type": 1,
        "pair": [
          "F",
          "H"
        ],
        "text": "can't live in the same room"
      },
      {
        "_id": 7,
        "type": 2,
        "pair": [
          "C",
          "F"
        ],
        "text": "must be neighbors"
      }
    ],
    "optimal": 596,
    "prop_sat": 5.358367626886145e-05,
    "sat_std_norm": 0.16116712146911408,
    "sat_std": 96.05560439559198,
    "min_sat_score": 247,
    "med_sat_score": 416.14444444444445,
    "med_sat_score_norm": 0.6982289336316182,
    "hc_gap_norm": 0.3959731543624161
  },
  {
    "payoff": {
      "A": {
        "101": 24,
        "102": 95,
        "103": 36,
        "104": 84,
        "105": 47,
        "106": 94
      },
      "B": {
        "101": 8,
        "102": 40,
        "103": 53,
        "104": 51,
        "105": 34,
        "106": 35
      },
      "C": {
        "101": 95,
        "102": 54,
        "103": 87,
        "104": 51,
        "105": 16,
        "106": 87
      },
      "D": {
        "101": 54,
        "102": 70,
        "103": 90,
        "104": 38,
        "105": 45,
        "106": 83
      },
      "E": {
        "101": 58,
        "102": 55,
        "103": 81,
        "104": 72,
        "105": 20,
        "106": 61
      },
      "F": {
        "101": 17,
        "102": 88,
        "103": 8,
        "104": 81,
        "105": 10,
        "106": 15
      },
      "G": {
        "101": 33,
        "102": 25,
        "103": 72,
        "104": 36,
        "105": 40,
        "106": 87
      },
      "H": {
        "101": 5,
        "102": 31,
        "103": 15,
        "104": 2,
        "105": 35,
        "106": 29
      }
    },
    "_id": "14549",
    "difficulty": "Hard",
    "students": [
      "A",
      "B",
      "C",
      "D",
      "E",
      "F",
      "G",
      "H"
    ],
    "rooms": [
      101,
      102,
      103,
      104,
      105,
      106
    ],
    "constraints": [
      {
        "_id": 0,
        "type": 2,
        "pair": [
          "C",
          "G"
        ],
        "text": "must be neighbors"
      },
      {
        "_id": 1,
        "type": 2,
        "pair": [
          "B",
          "H"
        ],
        "text": "must be neighbors"
      },
      {
        "_id": 2,
        "type": 1,
        "pair": [
          "A",
          "G"
        ],
        "text": "can't live in the same room"
      },
      {
        "_id": 3,
        "type": 2,
        "pair": [
          "B",
          "G"
        ],
        "text": "must be neighbors"
      },
      {
        "_id": 4,
        "type": 1,
        "pair": [
          "E",
          "H"
        ],
        "text": "can't live in the same room"
      },
      {
        "_id": 5,
        "type": 1,
        "pair": [
          "E",
          "G"
        ],
        "text": "can't live in the same room"
      },
      {
        "_id": 6,
        "type": 2,
        "pair": [
          "D",
          "E"
        ],
        "text": "must be neighbors"
      },
      {
        "_id": 7,
        "type": 0,
        "pair": [
          "D",
          "G"
        ],
        "text": "must live in the same room"
      }
    ],
    "optimal": 557,
    "prop_sat": 0.0010716735253772291,
    "sat_std_norm": 0.12532992558604442,
    "sat_std": 69.80876855142674,
    "min_sat_score": 178,
    "med_sat_score": 391.95,
    "med_sat_score_norm": 0.7036804308797128,
    "hc_gap_norm": 0.39676840215439857
  }
]